Feature/39524
harshsuccessive/javascript-server pull request #11
Opened 2020-11-02 13:28 UTC by harshsuccessive

created validation handler

2020-11-08 19:22 UTC, namanpar requested changes

2020-11-08 19:22 UTC, namanpar commented on src/controllers/trainee/validation.ts
> +        },
is this is validation file or config file

2020-11-08 19:22 UTC, namanpar commented on src/libs/validationHandler.ts
> +            if(req.method == 'POST' || req.method == 'PUT'){
use es6 and proper naming convention

2020-11-09 04:37 UTC, harshsuccessive commented on src/controllers/trainee/validation.ts
> +        },
it is a validation file and inside a constant config is defined as per the guidelines of user story on redmine

2020-11-09 04:37 UTC, harshsuccessive commented on src/libs/validationHandler.ts
> +            if(req.method == 'POST' || req.method == 'PUT'){
used es6 and and named it please check

2020-11-09 12:47 UTC, namanpar approved these changes

2020-11-09 12:55 UTC, merged