Feature/40009
harshsuccessive/javascript-server pull request #12
Opened 2020-11-03 13:55 UTC by harshsuccessive

Created an authmiddlerware.ts
to perform authentication and check authorization

2020-11-08 19:25 UTC, namanpar requested changes
resolve conflict and do the requested changes

2020-11-08 19:25 UTC, namanpar commented on extraTs/utils/validation.ts
>    export default function validateUser ( user: IUsers[] ): void {
use es6

2020-11-08 19:25 UTC, namanpar commented on src/controllers/trainee/controller.ts
> +    Delete( req: Request, res: Response, next: NextFunction ) {
proper function naming

2020-11-08 19:25 UTC, namanpar commented on src/libs/permission.ts
> +        }
improve this function logic and code, use es6

2020-11-08 19:25 UTC, namanpar commented on src/libs/routes/authMiddleWare.ts
> +        }
name the given function

2020-11-09 12:15 UTC, harshsuccessive commented on extraTs/utils/validation.ts
>    export default function validateUser ( user: IUsers[] ): void {
Shifted to es6

2020-11-09 12:15 UTC, harshsuccessive commented on src/controllers/trainee/controller.ts
> +    Delete( req: Request, res: Response, next: NextFunction ) {
changed the names

2020-11-09 12:57 UTC, harshsuccessive commented on src/libs/permission.ts
> +        }
changed the logic and code and shifted to es6

2020-11-09 13:01 UTC, harshsuccessive commented on src/libs/routes/authMiddleWare.ts
> +        }
named it

2020-11-10 07:02 UTC, namanpar requested changes
Fix lint and do requested changes

2020-11-10 07:02 UTC, namanpar commented on src/libs/permission.ts
> +    if (permission.all.includes(role)) {
declare method in es6

2020-11-10 07:51 UTC, harshsuccessive commented on src/libs/permission.ts
> +    if (permission.all.includes(role)) {
done

2020-11-17 07:55 UTC, namanpar approved these changes

2020-11-17 07:55 UTC, merged