Feature/39520
harshsuccessive/javascript-server pull request #7
Opened 2020-10-23 14:28 UTC by harshsuccessive

created typescript files
created interfaces

2020-10-25 21:19 UTC, namanpar commented on extraTs/utils/permissions.ts
> +        };
moduleName is of object type

2020-10-25 21:24 UTC, namanpar requested changes

2020-10-25 21:24 UTC, namanpar commented on extraTs/patterns/equilateral.ts
> +export default function equilateral (x: number): number
Is function is return number

2020-10-25 21:24 UTC, namanpar commented on extraTs/patterns/diamond.ts
> +export default function diamond(x: number): number
Is function returning a number

2020-10-25 21:24 UTC, namanpar commented on extraTs/index.ts
> +const user =[{
Give user variable a script type

2020-10-25 21:24 UTC, namanpar commented on extraTs/index.ts
> +
All import should be called earlier before function declaration or execution

2020-10-26 04:26 UTC, harshsuccessive commented on extraTs/patterns/equilateral.ts
> +export default function equilateral (x: number): number
yes sir when the condition is checked that n is in between 2 to 10 if it's not it will return 0

2020-10-26 04:26 UTC, harshsuccessive commented on extraTs/patterns/diamond.ts
> +export default function diamond(x: number): number
yes sir when the condition is checked that n is in between 2 to 10 if it's not it will return 0

2020-10-26 04:29 UTC, harshsuccessive commented on extraTs/utils/permissions.ts
> +        };
I'm passing the moduleName as a string

2020-10-26 19:11 UTC, namanpar requested changes
Kindly resolve conflict before commit

2020-10-26 19:11 UTC, namanpar commented on extra/patterns/diamond.js
>  export default function diamond(x)
Unresolved conflict

2020-10-26 19:11 UTC, namanpar commented on extra/patterns/equilateral.js
> +=======
Unresolved conflict

2020-10-26 19:11 UTC, namanpar commented on extra/utils/permissions.js
>  import {permissions} from '../constant'
Unresolved conflict

2020-10-27 08:16 UTC, harshsuccessive commented on extraTs/patterns/equilateral.ts
> +export default function equilateral (x: number): number
changed to void

2020-10-27 08:16 UTC, harshsuccessive commented on extraTs/patterns/diamond.ts
> +export default function diamond(x: number): number
changed to void

2020-10-27 08:17 UTC, harshsuccessive commented on extraTs/index.ts
> +const user =[{
given

2020-10-27 08:17 UTC, harshsuccessive commented on extraTs/index.ts
> +
shifted import functions before execution

2020-10-27 08:17 UTC, harshsuccessive commented on extra/patterns/diamond.js
>  export default function diamond(x)
Resolved the conflicts

2020-10-27 08:18 UTC, harshsuccessive commented on extra/patterns/equilateral.js
> +=======
resolved the conflict

2020-10-27 08:18 UTC, harshsuccessive commented on extra/utils/permissions.js
>  import {permissions} from '../constant'
resolved the conflict

2020-10-27 08:21 UTC, namanpar approved these changes

2020-10-27 08:21 UTC, merged