HTTP STATUS and Handler
harshsuccessive/javascript-server pull request #9
Opened 2020-10-28 08:04 UTC by harshsuccessive

Created a middleware
Created two files errorHandler.ts and notFoundRoute.ts
It shows the following error
{
error: "Not Found",
message: "error",
status: 500,
timestamp: "2019-01-08T17:38:21.929Z"
}

2020-10-28 13:13 UTC, namanpar requested changes
You should write proper name for functions. It is a good practice to export nameless function

2020-10-28 13:13 UTC, namanpar commented on src/libs/routes/notFoundRoute.ts
> +export default (req: Request, res: Response, next: NextFunction) =>{
Write proper name for function

2020-10-28 13:13 UTC, namanpar commented on src/libs/routes/errorHandler.ts
> +export default (err, req: Request, res: Response, next: NextFunction ) =>{
Write proper name for function

2020-10-28 16:54 UTC, harshsuccessive commented on src/libs/routes/notFoundRoute.ts
> +export default (req: Request, res: Response, next: NextFunction) =>{
Wrote the Name please do check

2020-10-28 16:54 UTC, harshsuccessive commented on src/libs/routes/errorHandler.ts
> +export default (err, req: Request, res: Response, next: NextFunction ) =>{
Wrote the name please do check

2020-10-29 12:18 UTC, namanpar approved these changes

2020-10-29 12:18 UTC, merged